In [1]:
import pandas as pd

In [2]:
pd.read_csv("../../data/raw/mlb_elo_latest.csv")

,date,season,neutral,playoff,team1,team2,elo1_pre,elo2_pre,elo_prob1,elo_prob2,...,pitcher1_rgs,pitcher2_rgs,pitcher1_adj,pitcher2_adj,rating_prob1,rating_prob2,rating1_post,rating2_post,score1,score2
0,2021-10-03,2021,0,NaN,ATL,NYM,1522.348303,1513.261073,0.547473,0.452527,...,NaN,NaN,NaN,NaN,0.519140,0.480860,NaN,NaN,NaN,NaN
1,2021-10-03,2021,0,NaN,STL,CHC,1491.709838,1496.087799,0.528208,0.471792,...,NaN,NaN,NaN,NaN,0.517334,0.482666,NaN,NaN,NaN,NaN
2,2021-10-03,2021,0,NaN,SEA,ANA,1489.919377,1496.383081,0.525215,0.474785,...,NaN,NaN,NaN,NaN,0.508962,0.491038,NaN,NaN,NaN,NaN
3,2021-10-03,2021,0,NaN,LAD,MIL,1585.624562,1525.029457,0.619392,0.380608,...,NaN,NaN,NaN,NaN,0.628774,0.371226,NaN,NaN,NaN,NaN
4,2021-10-03,2021,0,NaN,KCR,MIN,1443.484602,1486.044172,0.473316,0.526684,...,NaN,NaN,NaN,NaN,0.461883,0.538117,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2423,2021-04-01,2021,0,NaN,PHI,ATL,1499.854980,1537.334830,0.480611,0.519389,...,56.982418,53.435208,25.593166,-0.900219,0.537195,0.462805,1507.143856,1532.557621,3.0,2.0
2424,2021-04-01,2021,0,NaN,CHC,PIT,1510.606166,1466.885465,0.596242,0.403758,...,56.657868,47.268712,35.374576,-2.657647,0.687642,0.312358,1504.178744,1435.619713,3.0,5.0
2425,2021-04-01,2021,0,NaN,MIL,MIN,1502.386929,1522.960488,0.504931,0.495069,...,57.894228,57.914464,34.030150,17.163499,0.533019,0.466981,1518.710560,1536.695871,6.0,5.0
2426,2021-04-01,2021,0,NaN,DET,CLE,1450.437505,1513.164945,0.444496,0.555504,...,47.172259,61.318392,-0.833903,43.767481,0.378466,0.621534,1447.667412,1511.947362,3.0,2.0
2427,2021-04-01,2021,0,NaN,NYY,TOR,1540.629874,1499.393681,0.592794,0.407206,...,64.078782,55.252245,44.482355,35.170897,0.624955,0.375045,1570.975244,1520.453518,2.0,3.0